#单机
#server:
#  port: 8000
#spring:
#  application:
#    name: provider
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/
#  instance:
#    prefer-ip-address: true


#集群
server:
  port: 8000
spring:
  application:
    name: provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8761/eureka/
  instance:
    prefer-ip-address: true