server:
  port: 8040
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#自定义指定微服务的访问路径   
#zuul:
#  routes:
#    feign-consumer: /test/**

#忽略指定微服务
#zuul:
#  ignored-services: feign-consumer

# 忽略所有服务，只路由指定的服务
#zuul:
#  ignored-services: '*'   # 使用'*'可忽略所有微服务
#  routes:
#    feign-consumer: /test/**

#同时指定微服务的serviceId和对应的路径
#zuul:
#  routes:
#    user-route:                   # 该配置方式中，user-route只是给路由一个名称，可以任意起名。
#      service-id: feign-consumer
#      path: /test/**              # service-id对应的路径


#同时指定path和url
#zuul:
#  routes:
#    user-route:                   # 该配置方式中，user-route只是给路由一个名称，可以任意起名。
#      url: http://localhost:8000/ # 指定的url
#      path: /test/**              # url对应的路径。

#同时指定path和url 并且不破坏Zuul的Hystrix，Bibbon特性。
#zuul:
#  routes:
#    user-route:
#      path: /test/**
#      service-id: feign-consumer
#ribbon:
#  eureka:
#    enabled: false    # 禁用掉ribbon的eureka使用。
#feign-consumer:
#  ribbon:
#    listOfServers: localhost:8000,localhost:8001

#路由前缀
#zuul:
#  prefix: /api
#  routes:
#    feign-consumer: /test/**

#忽略某些路径
zuul:
  ignoredPatterns: /**/admin/**   # 忽略所有包括/admin/的路径
  routes:
    feign-consumer: /test/**

management:
  security:
    enabled: false

